language: python

python:
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - pylint -d E1101,C0413,C0415,R0401,R0903,R0201,R0913 department_app
  - coverage run --source=department_app -m unittest discover

after_success:
  - coveralls